version: '3'

services:
  redis:
    image: redis:alpine

  search: &search
    build: .
    links:
      - redis
    volumes:
      - ./src:/app
    ports:
      - "8080:8000"

  worker:
    <<: *search
    command: dramatiq tasks -t 2 -p 2 --watch .
    ports: []
