version: '3'

services:
  redis:
    image: redis:alpine

  search: &search
    build: .
    links:
      - redis
    volumes:
      - ./src:/app
    environment:
      MAX_HTTP_CONNECTIONS: ${MAX_HTTP_CONNECTIONS:-10}
    ports:
      - "8080:8000"

  worker:
    <<: *search
    command: /run-worker.sh
    ports: []
